
# Optimized Lambda Function Configurations for Biomerkin
# Generated by LambdaOptimizer


resource "aws_lambda_function" "biomerkin_genomics_agent" {
  function_name = "biomerkin-genomics-agent"
  memory_size   = 1024
  timeout       = 300
  
  environment {
    variables = {
    "PYTHONPATH": "/var/task",
    "BIOPYTHON_CACHE_SIZE": "100",
    "MAX_SEQUENCE_LENGTH": "1000000"
}
  }
  
  reserved_concurrent_executions = 10
  
  tags = {
    Name        = "biomerkin-genomics-agent"
    Environment = "production"
    Component   = "biomerkin-agent"
    Optimized   = "true"
  }
}

resource "aws_lambda_provisioned_concurrency_config" "biomerkin_genomics_agent_concurrency" {
  function_name                     = aws_lambda_function.biomerkin_genomics_agent.function_name
  provisioned_concurrent_executions = 2
  qualifier                         = "$LATEST"
}


resource "aws_lambda_function" "biomerkin_proteomics_agent" {
  function_name = "biomerkin-proteomics-agent"
  memory_size   = 768
  timeout       = 240
  
  environment {
    variables = {
    "PYTHONPATH": "/var/task",
    "PDB_API_TIMEOUT": "30",
    "PROTEIN_CACHE_SIZE": "50"
}
  }
  
  reserved_concurrent_executions = 8
  
  tags = {
    Name        = "biomerkin-proteomics-agent"
    Environment = "production"
    Component   = "biomerkin-agent"
    Optimized   = "true"
  }
}

resource "aws_lambda_provisioned_concurrency_config" "biomerkin_proteomics_agent_concurrency" {
  function_name                     = aws_lambda_function.biomerkin_proteomics_agent.function_name
  provisioned_concurrent_executions = 1
  qualifier                         = "$LATEST"
}


resource "aws_lambda_function" "biomerkin_literature_agent" {
  function_name = "biomerkin-literature-agent"
  memory_size   = 512
  timeout       = 180
  
  environment {
    variables = {
    "PYTHONPATH": "/var/task",
    "PUBMED_API_TIMEOUT": "30",
    "MAX_ARTICLES": "50",
    "BEDROCK_TIMEOUT": "60"
}
  }
  
  reserved_concurrent_executions = 15
  
  tags = {
    Name        = "biomerkin-literature-agent"
    Environment = "production"
    Component   = "biomerkin-agent"
    Optimized   = "true"
  }
}

resource "aws_lambda_provisioned_concurrency_config" "biomerkin_literature_agent_concurrency" {
  function_name                     = aws_lambda_function.biomerkin_literature_agent.function_name
  provisioned_concurrent_executions = 3
  qualifier                         = "$LATEST"
}


resource "aws_lambda_function" "biomerkin_drug_agent" {
  function_name = "biomerkin-drug-agent"
  memory_size   = 512
  timeout       = 180
  
  environment {
    variables = {
    "PYTHONPATH": "/var/task",
    "DRUGBANK_API_TIMEOUT": "30",
    "CLINICAL_TRIALS_TIMEOUT": "45"
}
  }
  
  reserved_concurrent_executions = 10
  
  tags = {
    Name        = "biomerkin-drug-agent"
    Environment = "production"
    Component   = "biomerkin-agent"
    Optimized   = "true"
  }
}

resource "aws_lambda_provisioned_concurrency_config" "biomerkin_drug_agent_concurrency" {
  function_name                     = aws_lambda_function.biomerkin_drug_agent.function_name
  provisioned_concurrent_executions = 2
  qualifier                         = "$LATEST"
}


resource "aws_lambda_function" "biomerkin_decision_agent" {
  function_name = "biomerkin-decision-agent"
  memory_size   = 1024
  timeout       = 300
  
  environment {
    variables = {
    "PYTHONPATH": "/var/task",
    "BEDROCK_TIMEOUT": "120",
    "REPORT_TEMPLATE_CACHE": "20"
}
  }
  
  reserved_concurrent_executions = 5
  
  tags = {
    Name        = "biomerkin-decision-agent"
    Environment = "production"
    Component   = "biomerkin-agent"
    Optimized   = "true"
  }
}

resource "aws_lambda_provisioned_concurrency_config" "biomerkin_decision_agent_concurrency" {
  function_name                     = aws_lambda_function.biomerkin_decision_agent.function_name
  provisioned_concurrent_executions = 1
  qualifier                         = "$LATEST"
}


resource "aws_lambda_function" "biomerkin_orchestrator" {
  function_name = "biomerkin-orchestrator"
  memory_size   = 768
  timeout       = 900
  
  environment {
    variables = {
    "PYTHONPATH": "/var/task",
    "MAX_CONCURRENT_AGENTS": "4",
    "WORKFLOW_TIMEOUT": "1800",
    "ENABLE_PARALLEL_EXECUTION": "true"
}
  }
  
  reserved_concurrent_executions = 20
  
  tags = {
    Name        = "biomerkin-orchestrator"
    Environment = "production"
    Component   = "biomerkin-agent"
    Optimized   = "true"
  }
}

resource "aws_lambda_provisioned_concurrency_config" "biomerkin_orchestrator_concurrency" {
  function_name                     = aws_lambda_function.biomerkin_orchestrator.function_name
  provisioned_concurrent_executions = 3
  qualifier                         = "$LATEST"
}

