
# Optimized Lambda Function Configurations for Biomerkin
# Generated by LambdaOptimizer

from aws_cdk import (
    Duration,
    aws_lambda as _lambda,
)

class OptimizedLambdaConfigs:
    """Optimized Lambda configurations for Biomerkin agents."""
    
    @staticmethod
    def get_function_configs():
        return {

            "biomerkin-genomics-agent": {
                "memory_size": 1024,
                "timeout": Duration.seconds(300),
                "environment": {
                "PYTHONPATH": "/var/task",
                "BIOPYTHON_CACHE_SIZE": "100",
                "MAX_SEQUENCE_LENGTH": "1000000"
},
                "reserved_concurrent_executions": 10,
                "description": "Optimized for DNA sequence analysis with Biopython"
            },
            "biomerkin-proteomics-agent": {
                "memory_size": 768,
                "timeout": Duration.seconds(240),
                "environment": {
                "PYTHONPATH": "/var/task",
                "PDB_API_TIMEOUT": "30",
                "PROTEIN_CACHE_SIZE": "50"
},
                "reserved_concurrent_executions": 8,
                "description": "Optimized for protein structure analysis"
            },
            "biomerkin-literature-agent": {
                "memory_size": 512,
                "timeout": Duration.seconds(180),
                "environment": {
                "PYTHONPATH": "/var/task",
                "PUBMED_API_TIMEOUT": "30",
                "MAX_ARTICLES": "50",
                "BEDROCK_TIMEOUT": "60"
},
                "reserved_concurrent_executions": 15,
                "description": "Optimized for literature search and AI summarization"
            },
            "biomerkin-drug-agent": {
                "memory_size": 512,
                "timeout": Duration.seconds(180),
                "environment": {
                "PYTHONPATH": "/var/task",
                "DRUGBANK_API_TIMEOUT": "30",
                "CLINICAL_TRIALS_TIMEOUT": "45"
},
                "reserved_concurrent_executions": 10,
                "description": "Optimized for drug discovery and clinical trial data"
            },
            "biomerkin-decision-agent": {
                "memory_size": 1024,
                "timeout": Duration.seconds(300),
                "environment": {
                "PYTHONPATH": "/var/task",
                "BEDROCK_TIMEOUT": "120",
                "REPORT_TEMPLATE_CACHE": "20"
},
                "reserved_concurrent_executions": 5,
                "description": "Optimized for medical report generation with Bedrock"
            },
            "biomerkin-orchestrator": {
                "memory_size": 768,
                "timeout": Duration.seconds(900),
                "environment": {
                "PYTHONPATH": "/var/task",
                "MAX_CONCURRENT_AGENTS": "4",
                "WORKFLOW_TIMEOUT": "1800",
                "ENABLE_PARALLEL_EXECUTION": "true"
},
                "reserved_concurrent_executions": 20,
                "description": "Optimized for workflow orchestration and agent coordination"
            },
        }
    
    @staticmethod
    def get_provisioned_concurrency_configs():
        return {

            "biomerkin-genomics-agent": 2,
            "biomerkin-proteomics-agent": 1,
            "biomerkin-literature-agent": 3,
            "biomerkin-drug-agent": 2,
            "biomerkin-decision-agent": 1,
            "biomerkin-orchestrator": 3,
        }
